apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
  clusterIP: 10.96.1.1
