
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service2
  name: service2
spec:
  type: NodePort
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 30007
  clusterIP: 10.96.1.2
