apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - image: spike433/service1:2.0
          name: service1
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred 

