# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
       # This path is specific to Ubuntu
       path: ~/.cache/pip
      # Look to see if there is a cache hit for the corresponding requirements file
       key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
       restore-keys: |
        ${{ runner.os }}-pip-
        ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
   
    - name: Create a temporary artifact downloads folder
      run: mkdir downloads
   
    - name: Add artifacts to publish to the temp folder (Run Unit, Integration Test)       
      run: |
          cd downloads
          echo "Unit Test passed" >> artifact.txt
          echo "Integration Test passed" >> artifact.txt    
          cd ..     
          
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: publish-artifacts
          path: downloads
