name: CI to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Smoke Test       
        run: |   
          chmod +x ./smokeTest/smoke-services.sh
          chmod +x ./smokeTest/smoke.sh
          ./smokeTest/smoke-services.sh >> artifact.txt                    
          cd ..    
